# Generated by Django 5.0.6 on 2024-07-06 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_persona_lugarresidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='lugarresidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ciudad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipodocumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.tipodocumento'),
        ),
    ]
